import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // ── Tutorials ────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Tutorials',
      collapsible: false,
      className: 'sidebar-section-header',
      items: [
        'intro',
        {
          type: 'category',
          label: 'Tutorials',
          link: {type: 'generated-index', description: 'Hands-on, end-to-end guides that walk through complete Topaz workflows with code samples, setup details, and troubleshooting tips.'},
          items: [{type: 'autogenerated', dirName: 'tutorials'}],
        },
      ],
    },
    // ── How-to guides ────────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'How-to guides',
      collapsible: false,
      className: 'sidebar-section-header',
      items: [
        'using-cli',
        {
          type: 'category',
          label: 'Ecosystem',
          link: {type: 'generated-index', slug: '/ecosystem'},
          items: [{type: 'autogenerated', dirName: 'ecosystem'}],
        },
        {
          type: 'category',
          label: 'Client SDKs',
          link: {type: 'generated-index', slug: '/client-sdks', description: 'Language-specific packages that make it easy to authenticate and interact with the Topaz emulator from test code and local development applications.'},
          items: [{type: 'autogenerated', dirName: 'client-sdks'}],
        },
        {
          type: 'category',
          label: 'Integrations',
          link: {type: 'generated-index'},
          items: [{type: 'autogenerated', dirName: 'integrations'}],
        },
        'mcp-server',
        'portal',
        'troubleshooting',
      ],
    },
    // ── Reference ────────────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      className: 'sidebar-section-header',
      items: [
        'supported-services',
        'compatibility',
        'endpoints',
        'known-limitations',
        {
          type: 'category',
          label: 'CLI reference',
          link: {type: 'generated-index'},
          items: [{type: 'autogenerated', dirName: 'cli-reference'}],
        },
        {
          type: 'category',
          label: 'API Coverage',
          link: {type: 'generated-index', description: 'Detailed coverage of Azure REST API operations implemented in Topaz, per service. Use this section to quickly see which operations are available and which are still pending implementation.'},
          items: [{type: 'autogenerated', dirName: 'api-coverage'}],
        },
      ],
    },
    // ── Explanation ───────────────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Explanation',
      collapsible: false,
      className: 'sidebar-section-header',
      items: [
        'local-azure-emulator',
        {
          type: 'category',
          label: 'Concepts',
          link: {type: 'generated-index', description: 'Background and conceptual material that explains how Topaz works, the decisions behind its design, and the Azure fundamentals that underpin it.'},
          items: [{type: 'autogenerated', dirName: 'concepts'}],
        },
        {
          type: 'category',
          label: 'Comparisons',
          link: {type: 'generated-index'},
          items: [{type: 'autogenerated', dirName: 'comparisons'}],
        },
        'chaos-engineering',
        {
          type: 'category',
          label: 'FinOps',
          link: {type: 'generated-index', description: 'Cost estimation and FinOps features powered by the ACE (Azure Cost Estimator) integration.'},
          items: [{type: 'autogenerated', dirName: 'finops'}],
        },
      ],
    },
  ],
};

export default sidebars;
