name: Publish new release

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The workflow run ID to download artifacts from'
        required: true
        type: string
  workflow_run:
    workflows: [Build_Test_And_Publish]
    types: [completed]

permissions:
  packages: write
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set run ID
      id: set-run-id
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "RUN_ID=${{ github.event.inputs.run_id }}" >> $GITHUB_OUTPUT
          echo "Using manually provided run ID: ${{ github.event.inputs.run_id }}"
        else
          echo "RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          echo "Using workflow_run event run ID: ${{ github.event.workflow_run.id }}"
        fi
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
        github-token: ${{ github.token }}
        run-id: ${{ steps.set-run-id.outputs.RUN_ID }}
    - name: Read tag info
      id: read-tag
      run: |
        TAG=$(cat tag-info/tag-info.txt)
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Using release tag: $TAG"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.read-tag.outputs.tag }}
        prerelease: true
        files: |
          *.zip
